### ISSUE TITLE
Allow copying of private messages and comments in activities

### ISSUE THREAD

**Issue by Trivernis** [AniTrend/anitrend-app#276]
## Feature Information 

When trying to highlight the text of an activity reply or of a private message it... Does not work. This is especially frustrating for URLs.

## Solution Information

Long press on the text -> the text gets highlighted and displays the default android text processing menu.

**Describe alternatives you've considered**
Using two phones and typing the content of the first one by using the second.

## Additional context
![IMG_20200716_070038.jpg](https://user-images.githubusercontent.com/19694973/87628856-23bb6f80-c732-11ea-9215-ba1d4fe1ef72.jpg)

**Comment by Trivernis** [comment]
Thank you, issue-label-san

**Comment by wax911** [comment]
Hey @Trivernis thank you for pointing that out, this has been an issue that hasn't been easy to work around since the text rendered on screen with anything that support markdown (messages, status, bio, synopsis, e.t.c) makes use of [Spanned](https://developer.android.com/reference/android/text/Spanned) which allow styling text at character or paragraph levels by providing access to components like TextPaint and Canvas.

There's a bit of a discussion here on: [Linkify textView and make text selectable - android](https://android.developreference.com/article/23665259/Linkify+textView+and+make+text+selectable) which might give some insight to what the issue maybe. I may take a crack at this again at a later point in time. 

> **Linkify** is a method of making things like urls, phone numbers, emails, e.t.c appear as links in what is otherwise plain text, this is done on the `TextView` widget level but one can set the level at which content can be linkified (This works well with plain text but as soon as I need to decorate text nodes e.g. markdown then plain html links not written in MD format just appear as plain text)

**Comment by wax911** [comment]
@youssefhabri might you have any suggestions?
