### ISSUE TITLE
UI changes

### ISSUE THREAD

**Issue by ShittyGuy** [AniTrend/anitrend-app#56]
I don't know if they are intended but these are the things that bugged me while using the app:

AniList uses a very consistent type of card view. The top left is used for the show's status and at the button, there's a color area for the important information with the score in the right corner. [Here](https://imgur.com/a/Pt9UaZt) are some examples of this.
AniTrend uses another design but sadly not consistent. The [AniTrend Hub](https://i.imgur.com/NTaWTHL.jpg) page, for example, shows the score in the top left corner and the information under the cover art, while [User List](https://i.imgur.com/3Cr7DGW.jpg) page is showing the title at the top, the status at the button left and the score at the button right.
I would appreciate a more consistent design.

The Hub page is using an out of 5 system even if the own raiting system is different, but I think someone already complained about this.

Another aspect would be, that the User List covers are looking like they have a dark layer overlayed. Should come clear if you compre [this](https://i.imgur.com/3Cr7DGW.jpg) with [this](https://i.imgur.com/hmUm1en.jpg).

Furthermore, I think it's really annoying, that the User Lists are using another page type than for example the Hub page: If you are at the User Lists you have this back button at the top left instead of the hamburger button. I would prefere the hamburger button for every page.

I think that the search could also be made more userfriendly. If you search for something it just shows a big "Search" at the top. It would be nice if you could see the [search term there](https://i.imgur.com/JxR4zpZ.jpg) and if you tap on it you are able to edit it. (The YouTube app, or almost every onther app, has this feature. Just look there if you don't understand what I mean.)

**Comment by Z-Dante** [comment]
>`Another aspect would be, that the User List covers are looking like they have a dark layer overlayed.`
Ye this is bothering me a bit about the current UI.. All the covers look a bit dark layered and colors look washed out in the user anime list.. 
And shouldn't there be an option to select year range ( like 2007-2017) in the discover anime page like the website instead of only being able to select 1 year?

**Comment by wax911** [comment]
Hi all, sorry for the late reply, currently swarmed with work:

@ShittyGuy Thanks for pointing those issues out, we've adjusted the design now for a more consistent look and feel so should be rolling out with the new update soon. The current design was an experiment on my end while I was still playing with the design. 

<img src="https://cdn.discordapp.com/attachments/314444307278856192/460437331002916894/unknown.png" width="280px" />

The rating system has been mentioned a couple of times and is something that will be done when I or the other contributors have time, I've also moved the media list into the same page as everything else in the navigation drawer.

Lastly regarding the search bar, yes I agree and this was how the app worked in previous versions (v0.9.9) but after the website mentioned that they'd be changing the API I was pressed for time to rewrite the application completely. Thus some features are still pending and also the reason why the application is still in beta :+1: but thank you for the constructive feedback

__N.B.__ Some features may not make it, simply because I don't have the time to devote into the app anymore
